import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "../components/Button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-start justify-center gap-5 p-4 ">
        <h3 className="text-5xl font-extrabold">
          Starting Template for Nexs.js projects with:
        </h3>
        <ul className="w-full list-inside list-disc px-4 text-2xl font-semibold text-gray-700">
          <li>Storybook</li>
          <li>react-generate-cli</li>
          <li>tailwindcss</li>
          <li>react-testing-library</li>
        </ul>
        <div className="mt-10 grid w-full place-items-center">
          <Button active={false} />
        </div>
      </main>
    </>
  );
};

export default Home;
